# Google Drive Mount

In [0]:
from google.colab import auth
auth.authenticate_user()
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

# Naver API

In [0]:
url = 'https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query='
headers = {'Content-Type':'application/json',
            'X-NCP-APIGW-API-KEY':'',
            'X-NCP-APIGW-API-KEY-ID':''}

def req(query):
    return requests.get(url + query, headers=headers)

# Google API

In [0]:
#google maps

apiKey = ''

for index, row in df.iterrows():
  
  url = 'https://maps.googleapis.com/maps/api/geocode/json?address={},+CA&key={}'.format(address, apiKey)
  
  #response = requests.get(url)
  #data = response.json()
  #lat = data['results'][0]['geometry']['location']['lat']
  #lng = data['results'][0]['geometry']['location']['lng']
   
  row.lat = lat
  row.lng = lng
  
df.to_csv('/content/arisu.csv')

# 서울시상수도사업본부

In [0]:
#아리수
import pandas as pd
import requests

#df = pd.read_csv('/content/arisu.csv', encoding='CP949', names=['address','lat','long'])
df = pd.read_csv('/content/arisu.csv', encoding='CP949')

for index, row in df.iterrows():
  address = row[0]
  
  resp = req(address)
  
  try:
    data = resp.json()
    lat = data['addresses'][0]['y'] #위도
    long = data['addresses'][0]['x'] #경도
    
    df.loc[index, 1] = lat
    df.loc[index, 2] = long
       
  except:
    continue
    
df.to_csv('/content/arisu_latlong.csv')

# K WATER

In [0]:
%cp /content/gdrive/My\ Drive/kwater.csv /content/kwater.csv

In [0]:
#kwater
import pandas as pd
import requests

path = '/content/gdrive/My Drive/'
name = 'kwater.csv'
df = pd.read_csv(path+name)

#drop index
df = df.drop([df.columns[0]], axis='columns') #drop index

#add column
#df['lat'] = 0
#df['long'] = 0

for index, row in df.iterrows():
  address = row[1]
    
  resp = req(address)
  
  try:
    data = resp.json()
    lat = data['addresses'][0]['y'] #위도
    long = data['addresses'][0]['x'] #경도
    
    df.loc[index, 'lat'] = lat
    df.loc[index, 'long'] = long
    
    print(index, address, lat, long)
       
  except:
    continue
    
df.to_csv(path+'kwater_latlong.csv')

0 경기도 과천시 문원동 46-5 37.4211400 127.0038207
1 경기도 동두천시 생연동 70 37.9003108 127.0697804
2 경기도 의왕시 오전동 78-8 37.3658195 126.9671148
3 전라남도 순천시 가곡동 114-1 34.9865996 127.4834965
4 부산광역시 부산진구 가야동 10 35.1531710 129.0444728
5 대전광역시 중구 석교동 269-19 36.3047354 127.4382956
6 충청북도 영동군 영동읍 심원리88-4 36.2104328 127.8301707
9 부산광역시 부산진구 가야동 81 35.1559041 129.0350579
12 전라남도 순천시 남정동 12-1 34.9365086 127.4875247
14 인천광역시 서구 가정동 143 37.5287882 126.6711075
15 인천광역시 서구 마전동 49 37.6157343 126.6588678
17 경상남도 사천시 동동 1 34.9354528 128.0703362
19 경기도 포천시 영북면 운천리5 38.0817159 127.2964678
23 대전광역시 서구 갈마동 414-1 36.3454471 127.3641289
26 부산광역시 동구 수정동 23 35.1281531 129.0468430
27 서울특별시 금천구 시흥동 118 37.4549894 126.8971601
29 인천광역시 남동구 만수동 1-4 37.4694558 126.7323601
33 경상남도 거창군 신원면 과정리13 35.5706455 127.9318913
34 경기도 군포시 산본동 119 37.3427486 126.9281040
35 경기도 오산시 서동 10-1 37.1560314 127.0428674
36 경기도 구리시 아천동 49-1 37.5586148 127.1056641
37 서울특별시 강동구 강일동 8-1 37.5599644 127.1772655
38 서울특별시 구로구 개봉동 53-3 37.5022443 126.8413380
39 서울특별시 강남구 개포동 53-40 37.4721231 127.0598723
40 서울특별시 강남구 개포동 139 37.4831168 127.0660755
41 서울특별시 강서구 방화동 산152-1 (방화3동) 37.5803245 126.8079998
42 강원도 인제군 인제읍 38.0703920 128.1721880
44 서울특별시 은평구 녹번동 1-1 37.6100395 126.9400201
45 강원도 정선군 신동읍 37.2122023 128.6420711
47 부산광역시 사상구 주례동 113 35.1616328 129.0058378
49 강원도 태백시 철암동 3-3 37.1314864 129.0404370
53 인천광역시 서구 검암동 산71-3 37.5632430 126.6783124
55 경상남도 김해시 외동 47 35.2273913 128.8722086
56 경상남도 김해시 외동 824 35.2379165 128.8514408
57 강원도 강릉시 회산동 81 37.7410675 128.8709050
59 경기도 시흥시 신천동 산13 37.4476850 126.7792084
60 강원도 태백시 장성동 17-4 37.1040255 129.0094841
63 인천광역시 계양구 계산동 산52 37.5503758 126.7142527
65 대전광역시 대덕구 법동 17 36.3733367 127.4354241
67 서울특별시 강동구 고덕동 497 37.5580318 127.1523651
68 경기도 양주시 고암동 산67-1 37.8142460 127.0700420
70 전라남도 여수시 시전동 54 34.7588651 127.6865994
72 부산광역시 부산진구 당감동 34 35.1698886 129.0135993
74 부산광역시 해운대구 재송동 51-1 35.1887289 129.1354524
75 대전광역시 중구 문화동 18-1 36.2993276 127.4194062
76 강원도 양양군 양양읍 38.0806580 128.6240000
79 경기도 하남시 창우동 26-1 37.5265562 127.2410488
80 부산광역시 부산진구 범천동 44 35.1442493 129.0499973
83 경기도 양주시 회정동 44-3 37.8345918 127.0436072
87 부산광역시 해운대구 반여동 4-11 35.1993598 129.1372499
88 경기도 수원시영통구 이의동 127-8 37.2851289 127.0560356
89 서울특별시 강동구 암사동 10 37.5651022 127.1443543
91 충청남도 예산군 덕산면 36.7014850 126.6655000
92 서울특별시 노원구 상계동 53 37.6799956 127.0668825
93 전라남도 광양시 광영동 61-2 34.9650401 127.7050753
95 경상남도 김해시 삼방동 120-1 35.2669899 128.9162762
96 경기도 군포시 산본동 60 37.3607449 126.9159622
98 광주광역시 동구 운림동 92-1 35.1322867 126.9615239
101 경기도 김포시 양촌읍 구래리98-2 37.6455772 126.6101513
102 서울특별시 서초구 염곡동 2-1 37.4689052 127.0502066
103 서울특별시 서초구 염곡동 산39-4 (내곡동) 37.4616403 127.0597915
104 강원도 원주시 태장동 19 37.3716932 127.9665883
105 서울특별시 강남구 개포동 217-4 37.4718849 127.0531928
106 충청북도 청주시 서원구 산남동 산20-6 20-6 36.6196897 127.4647803
108 서울특별시 강남구 개포동 53-28 37.4732407 127.0712286
109 서울특별시 강남구 개포동 53-28 37.4732407 127.0712286
110 경기도 광명시 노온사동 37.4411000 126.8520000
115 강원도 철원군 서면 38.1647154 127.4158500
116 대전광역시 대덕구 중리동 388-17 36.3631658 127.4279712
120 대전광역시 서구 도마동 27-1 36.3194873 127.3632704
121 경기도 용인시 처인구 역북동 산15 37.2533776 127.1927558
123 경기도 이천시 관고동 67-3 37.2827937 127.4363011
124 서울특별시 노원구 상계동 1-2 37.6875795 127.0701574
126 강원도 동해시 망상동 37.5897900 129.0822500
128 서울특별시 동작구 상도동 65-41 37.4939794 126.9411001
129 경기도 광주시 중부면 산성리 37.4774907 127.1825301
130 강원도 원주시 행구동 98 37.3342475 128.0134819
131 서울특별시 구로구 궁동 10-49 37.5018212 126.8353846
133 인천광역시 남동구 장수동 22-4 37.4625927 126.7729683
135 경기도 양주시 덕계동 64 37.8082492 127.0616153
136 부산광역시 동래구 온천동 190-7 35.2178331 129.0797225
137 부산광역시 동래구 온천동 190-9 35.2092300 129.0541584
139 부산광역시 북구 금곡동 80 35.2617992 129.0216742
143 경기도 광명시 하안동 141-3 37.4554808 126.8791166
144 부산광역시 부산진구 전포동 29 35.1575053 129.0788008
146 부산광역시 동래구 사직동 12-5 35.2065585 129.0521725
147 울산광역시 울주군 온산읍 덕신리 258 35.4297564 129.3001395
148 부산광역시 금정구 부곡동 30-1 35.2344973 129.0976974
150 부산광역시 금정구 장전동 산29-4 35.2319809 129.0664370
151 경기도 포천시 수입리 483-2 37.9828671 127.3186578
152 강원도 철원군 동송읍 38.2071429 127.2081499
153 경기도 의정부시 자일동 92-3 37.7715465 127.1080113
156 전라남도 영암군 미암면 34.6992679 126.5717875
157 부산광역시 사하구 감천동 6-1723 35.0957595 129.0075515
158 경기도 부천시원미구 춘의동 산60-1 37.4976678 126.8096018
159 대전광역시 중구 사정동 198-2 36.2995646 127.3991898
161 강원도 영월군 수주면 도원리 37.3294750 128.2287750
163 서울특별시 강서구 방화동 110 37.5788888 126.8196062
164 경기도 이천시 관고동 67-3 37.2827937 127.4363011
166 대전광역시 대덕구 비래동 8-4 36.3554537 127.4593483
167 경기도 광주시 중부면 산성리 1098 1098 37.4763575 127.1831637
168 대전광역시 중구 사정동 2-1 36.3001195 127.4092841
169 부산광역시 서구 남부민동 428-79 35.0845691 129.0184256
170 경상북도 경주시 남산동 36-1 35.7879067 129.2268289
173 서울특별시 중랑구 망우동 71 37.6058626 127.1099011
174 서울특별시 용산구 한남동 10-77 37.5448785 126.9996609
175 서울특별시 용산구 이태원동 1-5 37.5452382 126.9928948
176 경상남도 고성군 고성읍 동외리369-2 34.9703807 128.3263237
177 충청남도 서천군 서천읍 36.0778106 126.6898896
178 전라남도 순천시 덕월동 115 34.9360161 127.4730132
179 서울특별시 금천구 시흥동 6-8 37.4371998 126.9080599
180 경기도 남양주시 호평동 73-1 37.6584122 127.2517424
181 경상북도 상주시 남장동 63-2 36.4070072 128.1278329
182 경상남도 김해시 동상동 1-2 35.2506914 128.8845411
183 강원도 인제군 남면 남전리 38.0076000 128.1556000
184 부산광역시 사하구 다대동 1-16 35.0528433 128.9924920
185 충청북도 보은군 내북면 성암리15-2 36.5811512 127.6760405
186 경기도 의왕시 내손동 61 37.3737113 126.9948134
188 대전광역시 서구 도마동 7-9 36.3230394 127.3611349
189 부산광역시 남구 대연동 54-37 35.1531485 129.0856547
192 강원도 양구군 양구읍 죽곡리 38.1348987 128.0076375
193 충청남도 태안군 태안읍 36.7576170 126.2963750
194 전라남도 영암군 금정면 34.8631242 126.7489896
195 충청북도 단양군 단성면 장회리21-7 36.9324502 128.2581214
197 강원도 태백시 하사미동 7-2 37.3070100 128.9956772
198 광주광역시 동구 운림동 132-1 35.1337613 126.9817837
199 충청북도 청원군 현도면 노산리 461-3 36.4509030 127.4521251
200 충청북도 청원군 현도면 노산리 산86-1 36.4677595 127.4515307
201 충청남도 논산시 노성면 36.2781500 127.1302500
202 서울특별시 노원구 상계동 53 37.6799956 127.0668825
203 서울특별시 성북구 성북동 25-1 37.5972219 126.9953255
204 부산광역시 강서구 녹산동 12 35.1246125 128.8962894
205 서울특별시 은평구 녹번동 1-1 37.6100395 126.9400201
206 서울특별시 은평구 응암동 37-54 (응암2동) 37.5977263 126.9333860
207 서울특별시 동작구 사당동 21-1 37.4922635 126.9715529
208 부산광역시 금정구 구서동 4-1 35.2593936 129.1030173
210 경기도 시흥시 능곡동 617 37.3679795 126.8162667
213 경기도 군포시 산본동 1065 37.3716487 126.9313149
214 경기도 고양시일산동구 식사동 425-3 37.6737412 126.8189228
215 경기도 포천시 영중면 양문리16-1 37.9966076 127.2657566
216 서울특별시 양천구 신정동 37-84 37.5149531 126.8517858
219 경기도 군포시 금정동 871-15 37.3501415 126.9306877
221 강원도 동해시 망상동 3 37.5790799 129.1040429
224 서울특별시 동작구 흑석동 60-6 37.5042941 126.9645085
226 서울특별시 강남구 개포동 1271 37.4777151 127.0523362
227 강원도 홍천군 홍천읍 갈마곡리67-13 37.6903334 127.9008787
228 경기도 군포시 당동 산 39-31 37.3532626 126.9392942
230 전라북도 순창군 풍산면 금곡리73-1 35.3186254 127.1393859
231 광주광역시 남구 봉선동 587 35.1184020 126.9108888
235 부산광역시 동래구 온천동 92-2 35.2146666 129.0610241
238 서울특별시 강남구 개포동 118-21 37.4748125 127.0693087
240 서울특별시 강남구 일원동 63-29 37.4795469 127.0817096
241 경상남도 사천시 대방동 2 34.9392540 128.0591367
242 대전광역시 중구 대사동 3-71 36.3044397 127.4225350
244 부산광역시 서구 동대신동3가 2-2 35.1238557 129.0186959
245 부산광역시 서구 동대신동3가 산2-2일원 35.1238557 129.0186959
246 부산광역시 서구 동대신동3가 2-2 35.1238557 129.0186959
247 부산광역시 서구 동대신동3가 2-2 35.1238557 129.0186959
248 부산광역시 서구 동대신동3가 2-2 35.1238557 129.0186959
249 부산광역시 서구 동대신동3가 2-2 35.1238557 129.0186959
251 강원도 양구군 해안면 38.2851000 128.1371000
252 부산광역시 남구 대연동 54-56 35.1445640 129.0938422
254 서울특별시 강남구 개포동 53-31 37.4725351 127.0694339
255 대전광역시 대덕구 평촌동 1 36.4333753 127.4428890
256 대전광역시 대덕구 미호동 692 36.4539388 127.4653676
260 경기도 의왕시 월암동 421 37.3141956 126.9595603
262 서울특별시 서대문구 연희동 2-17 37.5715756 126.9422765
263 부산광역시 북구 덕천동 814-1 35.2174173 129.0206336
265 경기도 부천시 오정구 여월동 산30-1 30-1 37.5121348 126.7907797
266 경기도 광명시 광명동 66-4 37.4841971 126.8599176
271 강원도 정선군 사북읍 사북리 37.2200000 128.8016000
272 서울특별시 노원구 상계동 84-26 37.6645027 127.0761617
275 경상남도 거제시 고현동 340 34.8811360 128.6314172
279 경상북도 문경시 점촌동 15-10 36.6016769 128.1925571
280 부산광역시 사하구 괴정동 1-1 35.1044277 129.0092994
281 충청남도 계룡시 금암동 58 36.2724792 127.2587829
282 서울특별시 강동구 상일동 54-1 37.5521377 127.1771930
284 서울특별시 노원구 상계동 155-1 37.6639745 127.0710883
286 서울특별시 중랑구 망우동 69-1 37.5942264 127.1055861
288 부산광역시 북구 만덕2동 산121 35.2019606 129.0425404
289 경기도 동두천시 보산동 13-1 37.9192645 127.0727561
290 인천광역시 서구 가정동 9-2 37.5338792 126.6759249
291 울산광역시 동구 동부동 120-2 35.5449805 129.4320937
292 충청남도 공주시 반포면 36.3968990 127.2502380
293 경기도 안성시 양성면 동항리 산63 37.0595984 127.1896766
294 대구광역시 동구 도학동 35 35.9929023 128.7042820
295 경기도 구리시 교문동 148 37.5947719 127.1363741
296 부산광역시 영도구 동삼동 29-5 35.0569442 129.0810688
298 대전광역시 서구 도마동 7 36.3252547 127.3627124
299 경기도 파주시 파평면 덕천리395 37.9409691 126.8703846
300 서울특별시 강동구 둔촌동 11-6 37.5291139 127.1516110
301 서울특별시 강동구 둔촌동 153 37.5305829 127.1527888
302 서울특별시 강동구 둔촌동 153 37.5305829 127.1527888
304 전라남도 순천시 금곡동 31 34.9653135 127.4689703
306 부산광역시 부산진구 개금동 21-1 35.1589794 129.0231616
308 충청북도 제천시 천남동 200 37.1379454 128.1868591
309 경기도 과천시 중앙동 11 37.4324257 126.9883162
310 경기도 과천시 중앙동 11 37.4324257 126.9883162
313 전라남도 화순군 동복면 35.0711920 127.1290750
314 경기도 안성시 봉남동 48 37.0119510 127.2793836
315 전라남도 광양시 마동 91-23 34.9529687 127.7025986
318 부산광역시 사하구 괴정동 173 35.1088801 128.9874293
319 강원도 태백시 황지동 5-1 37.1791290 128.9901703
320 충청북도 충주시 종민동 6-1 36.9863045 127.9841431
321 경상북도 문경시 불정동 339-8 36.6219693 128.1359546
322 강원도 영월군 북면 37.2545170 128.4551250
323 경기도 의정부시 용현동 61 37.7307738 127.0863505
325 부산광역시 동구 범일동 65-121 35.1416292 129.0393922
326 서울특별시 은평구 신사동 산93-16 (신사2동) 37.5909317 126.9010718
327 서울특별시 관악구 봉천동 4-9 37.4902852 126.9586969
329 경기도 동두천시 상패동 36 37.9141400 127.0433223
330 부산광역시 동구 초량동 26 35.1279424 129.0304740
331 부산광역시 동래구 온천동 190-8 35.2106331 129.0533091
333 부산광역시 북구 만덕동 152-2 35.1988593 129.0324577
334 부산광역시 부산진구 전포동 2-1 35.1597277 129.0770581
335 부산광역시 부산진구 초읍동 98-1 35.1887713 129.0275593
336 부산광역시 북구 만덕동 3 35.2166772 129.0469750
337 서울특별시 금천구 독산동 8 37.4744859 126.9091809
338 서울특별시 서대문구 봉원동 2-1 37.5741964 126.9481331
339 서울특별시 종로구 옥인동 3-14 37.5853125 126.9607916
342 인천광역시 남동구 간석3동 산27-1 37.4691289 126.7156547
344 부산광역시 부산진구 개금동 산11 35.1637730 129.0211987
347 강원도 철원군 갈말읍 38.1475820 127.3083250
349 전라남도 순천시 용당동 8-1 34.9798803 127.5043808
351 서울특별시 중랑구 망우동 57-3 37.5941469 127.1100352
352 강원도 화천군 간동면 38.0552920 127.7899000
353 경기도 안양시 동안구 비산3동 산113 37.4090578 126.9415521
354 서울특별시 양천구 신정동 140-3 37.5057184 126.8397205
355 경기도 과천시 문원동 58-2 37.4207222 127.0120592
356 경기도 과천시 문원동 58-2 37.4207222 127.0120592
357 서울특별시 강남구 도곡동 31-3 37.4902031 127.0463897
361 충청북도 청주시 서원구 모충동 산36-48 36-48 36.6240389 127.4756551
363 경상북도 문경시 모전동 620-3 36.5960265 128.1823614
364 충청북도 음성군 삼성면 양덕리 72 37.0430515 127.4933929
366 충청남도 공주시 반포면 36.3968990 127.2502380
368 서울특별시 서대문구 연희동 2-2 37.5794953 126.9414311
369 서울특별시 중랑구 묵동 산41-7 (묵1동) 37.6146746 127.0849498
370 강원도 태백시 동점동 6-5 37.1046933 129.0727359
371 서울특별시 중랑구 면목동 49-1 37.5858943 127.0979362
373 경기도 양주시 덕계동 707-25 37.8143960 127.0410013
374 대전광역시 중구 부사동 2-13 36.3060116 127.4304557
376 대전광역시 서구 정림동 18-1 36.3077245 127.3686357
377 서울특별시 서대문구 연희동 2-17 37.5715756 126.9422765
378 경기도 의왕시 오전동 산 175-1 37.3588089 126.9767698
379 강원도 양양군 양양읍 38.0806580 128.6240000
380 대전광역시 동구 이사동 7-1 36.2903286 127.4524908
381 부산광역시 영도구 동삼동 149-1 35.0805295 129.0601911
382 경기도 시흥시 목감동 19 37.3995878 126.8752235
383 부산광역시 사하구 다대동 144 35.0402418 128.9699069
384 서울특별시 강남구 자곡동 39-10 37.4751368 127.0934654
385 충청북도 제천시 강제동 668-1 37.1154723 128.1883283
390 경기도 과천시 문원동 10 37.4303782 127.0022167
391 경기도 남양주시 금곡동 126-1 37.6246167 127.2110221
392 경기도 포천시 신북면 가채리45-11 37.9174652 127.1878100
393 경기도 포천시 신북면 가채리46-42 37.9059779 127.1943570
394 울산광역시 북구 연암동 48 35.5864198 129.3895564
395 경기도 안성시 서운면 송정리301-1 36.9242052 127.2332190
396 서울특별시 종로구 무악동 48 37.5780219 126.9566661
398 경기도 동두천시 안흥동 71 37.9301521 127.0443480
399 경기도 의정부시 낙양동 38-1 37.7574419 127.1296542
403 경기도 과천시 문원동 15 37.4297230 127.0019484
404 인천광역시 남구 문학동 46 37.4404686 126.6878443
405 부산광역시 남구 문현동 7 35.1470100 129.0807399
406 강원도 태백시 동점동 6-5 37.1046933 129.0727359
407 경상남도 김해시 구산동 638 35.2535729 128.8788081
408 부산광역시 금정구 구서동 4-8 35.2596733 129.1030575
409 경기도 이천시 부발읍 마암리 산 24 37.2749533 127.4824996
410 강원도 정선군 고한읍 37.2086930 128.8430500
411 경기도 과천시 과천동 79-2 37.4567726 126.9930057
415 부산광역시 영도구 동삼동 149-1 35.0805295 129.0601911
416 부산광역시 동구 수정동 37 35.1311197 129.0311473
417 경기도 의정부시 장암동 82-1 37.7098783 127.0534524
418 경기도 오산시 수청동 41 37.1660860 127.0674605
420 부산광역시 해운대구 석대동 15 35.2324626 129.1389014
421 부산광역시 해운대구 반여동 110-2 35.2033530 129.1368033
424 강원도 원주시 봉산동 96-2 37.3521221 127.9844518
426 강원도 인제군 기린면 방동리 37.9254000 128.4052000
427 서울특별시 서초구 방배동 43-6 37.4776632 126.9971360
428 대전광역시 대덕구 비래동 34-19 36.3539400 127.4628533
432 서울특별시 양천구 신월동 160-2 37.5173426 126.8259406
434 부산광역시 사상구 엄궁동 52 35.1284685 128.9804485
435 서울특별시 서대문구 홍은동 19-1 37.5986725 126.9455170
436 부산광역시 북구 만덕동 149 35.2001919 129.0374292
437 경기도 남양주시 평내동 118 37.6510221 127.2394454
438 서울특별시 종로구 부암동 109-2 37.5999089 126.9695745
439 부산광역시 부산진구 당감동 34 35.1698886 129.0135993
440 부산광역시 부산진구 당감동 34 35.1698886 129.0135993
441 부산광역시 북구 만덕동 149 35.2001919 129.0374292
442 서울특별시 서대문구 홍제동 33-44 37.5778764 126.9469852
443 부산광역시 사상구 주례동 113-11 35.1596168 129.0014497
444 전라남도 장성군 북하면 35.4073737 126.8796000
445 부산광역시 북구 구포동 48-135 35.1964623 129.0164017
446 부산광역시 사상구 주례동 8-1 35.1575667 129.0090924
447 부산광역시 동구 수정동 17 35.1286074 129.0472085
448 경기도 평택시 월곡동 산27 37.0220081 127.1502146
450 인천광역시 부평구 일신동 62 37.4828331 126.7462213
451 경기도 이천시 장호원읍 진암리 산 112 37.1027539 127.6080835
452 부산광역시 북구 구포동 3-1 35.2041726 129.0116570
453 충청남도 태안군 태안읍 36.7576170 126.2963750
454 경기도 양주시 유양동 산40 37.7950169 127.0261694
456 인천광역시 부평구 구산동 6 37.4712391 126.7615761
457 경기도 오산시 벌음동 38 37.1431764 127.0383749
459 경기도 이천시 신둔면 남정리 산 27-1 37.3245705 127.4062052
460 충청북도 충주시 호암동 2 36.9575296 127.9465396
461 인천광역시 연수구 선학동 산71-1 37.4273980 126.6900275
462 부산광역시 북구 구포동 1245 35.1944273 129.0141776
463 충청북도 청주시흥덕구 가경동 762 36.6321261 127.4332577
464 서울특별시 노원구 상계동 42-1 37.6729058 127.0838519
466 인천광역시 연수구 청학동산55-4 37.4215419 126.6622847
467 부산광역시 북구 만덕동 77-1 35.2115823 129.0462178
468 부산광역시 금정구 장전동 산29-4 35.2319809 129.0664370
471 대전광역시 유성구 송강동 280 36.4364504 127.3809002
472 부산광역시 사하구 장림동 96-1 35.0683461 128.9655882
473 서울특별시 동작구 신대방동 143 37.4906480 126.9141220
474 서울특별시 노원구 상계동 686 37.6609271 127.0641847
477 대전광역시 중구 대사동 3-71 36.3044397 127.4225350
478 경기도 동두천시 생연동 15-5 37.9110519 127.0687235
479 대전광역시 중구 대사동 3-71 36.3044397 127.4225350
480 대전광역시 중구 대사동 산3-71 36.3044397 127.4225350
483 경기도 의왕시 오전동 166 37.3558192 126.9636597
485 경기도 동두천시 안흥동 70 37.9205835 127.0478711
487 강원도 원주시 태장동 191 37.3689308 127.9619263
490 서울특별시 서대문구 북아현동 1-1616 37.5674579 126.9520120
491 부산광역시 영도구 동삼동 29-5 35.0569442 129.0810688
492 부산광역시 사상구 주례동 69-1 35.1504306 129.0118832
493 부산광역시 영도구 신선동3가 6 35.0857818 129.0441246
495 경기도 의정부시 자일동 48-3 37.7739111 127.1120689
496 서울특별시 서대문구 봉원동 2-1 37.5741964 126.9481331
502 충청남도 서천군 한산면 용산리159 36.0620327 126.8425291
504 부산광역시 연제구 연산동 180-1 35.1616423 129.0855895
505 경기도 안양시만안구 안양8동 산133-6 37.3813728 126.9261194
506 서울특별시 노원구 중계동 산101-1 (중계4동) 37.6591698 127.0878458
509 서울특별시 강서구 화곡동 5-4 37.5402981 126.8596605
510 경상남도 창원시마산회원구 회원2동 산31-1 35.2244882 128.5566115
512 충청남도 당진시 송산면 36.9325846 126.6790750
513 서울특별시 서대문구 홍제동 33-44 37.5778764 126.9469852
514 인천광역시 부평구 부평동 54-16 37.4766334 126.7301354
516 경기도 의정부시 호원동 119-151 37.7088357 127.0446392
517 경상남도 양산시 북정동 35 35.3568266 129.0510250
518 서울특별시 강북구 수유동 37.6302774 127.0176581
519 서울특별시 강북구 수유동 37.6302774 127.0176581
520 서울특별시 강북구 수유동 37.6302774 127.0176581
521 서울특별시 성북구 정릉동 37.6014559 127.0166699
522 서울특별시 도봉구 도봉동 37.6786913 127.0434369
523 서울특별시 강북구 수유동 37.6302774 127.0176581
524 서울특별시 강북구 수유동 37.6302774 127.0176581
525 서울특별시 강북구 우이동 37.6632600 127.0004400
526 서울특별시 성북구 정릉동 37.6014559 127.0166699
527 서울특별시 성북구 정릉동 37.6014559 127.0166699
528 서울특별시 도봉구 도봉동 37.6786913 127.0434369
529 서울특별시 강북구 수유동 37.6302774 127.0176581
530 서울특별시 성북구 정릉동 37.6014559 127.0166699
531 서울특별시 성북구 정릉동 37.6014559 127.0166699
532 서울특별시 강북구 우이동 37.6632600 127.0004400
533 서울특별시 강북구 수유동 37.6302774 127.0176581
534 서울특별시 도봉구 도봉동 37.6786913 127.0434369
535 서울특별시 종로구 평창동 37.6063166 126.9681871
536 서울특별시 성북구 정릉동 37.6014559 127.0166699
540 서울특별시 강남구 일원동 441 37.4775325 127.0753509
541 경기도 의정부시 가능동 산81-2 37.7257360 127.0207328
542 인천광역시 남동구 만수동 2-2 37.4652336 126.7391830
543 인천광역시 서구 불로동산59-1 37.6120989 126.6938364
544 서울특별시 금천구 시흥동 6-7 37.4399840 126.9106454
545 부산광역시 사상구 엄궁동 42 35.1287542 128.9758929
546 경기도 의정부시 녹양동 산2-10 37.7547962 127.0483479
547 서울특별시 노원구 중계동 101-1 37.6591698 127.0878458
548 서울특별시 노원구 상계동 164-9 37.6671760 127.0834861
550 대전광역시 대덕구 비래동 1-15 36.3570092 127.4643182
551 경기도 안성시 명륜동 1-1 37.0157537 127.2756135
552 경기도 안성시 명륜동 1-1 37.0157537 127.2756135
555 강원도 홍천군 속초리 산28 37.6711742 127.9826108
556 대전광역시 서구 가수원동 618-4 36.2923052 127.3497927
557 경기도 의정부시 가능동 81-2 37.7556592 127.0436846
558 경기도 의왕시 오전동 산 148-11 37.3509603 126.9806218
561 경기도 과천시 문원동 58-9 37.4170442 127.0076858
562 경기도 과천시 문원동 58-10 37.4161604 127.0100361
564 경기도 안산시상록구 사동 산179 37.2898604 126.8317158
566 강원도 철원군 동송읍 38.2071429 127.2081499
567 경기도 이천시 관고동 67-3 37.2827937 127.4363011
570 경기도 평택시 지산동 143 37.0762287 127.0927185
571 부산광역시 동래구 명장동 94-3 35.2104599 129.0931365
572 충청북도 제천시 모산동 25 37.1750103 128.2143440
574 경기도 군포시 산본동 840-156 37.3564417 126.9140999
575 서울특별시 종로구 옥인동 179-1 37.5838104 126.9645119
577 서울특별시 금천구 시흥동 75 37.4446939 126.9138453
578 인천광역시 부평구 산곡동 산98 37.5049220 126.6929490
583 충청북도 청주시상당구 36.6347450 127.4886010
584 경기도 시흥시 하중동 2-3 37.4100229 126.8023782
585 서울특별시 노원구 상계동 145-24 37.6691017 127.0686852
587 서울특별시 관악구 신림동 57-13 37.4559322 126.9249239
588 광주광역시 북구 금곡동 800 35.1440891 126.9894567
589 대전광역시 유성구 원내동 716 36.2966052 127.3150611
590 부산광역시 영도구 신선동1가 12 35.0924675 129.0466426
591 광주광역시 광산구 산정동 53 35.1743217 126.7834982
593 부산광역시 사상구 괘법동 1 35.1720033 128.9977800
594 부산광역시 금정구 장전동 30 35.2352788 129.0681757
595 경기도 여주시 월송동 35-1 37.2921798 127.6236055
596 부산광역시 수영구 망미동 107-1 35.1671018 129.0999093
597 부산광역시 해운대구 반여동 300 35.2081328 129.1141094
598 부산광역시 해운대구 반여동 300 35.2081328 129.1141094
602 부산광역시 북구 만덕동 843 35.2067852 129.0370450
603 서울특별시 금천구 시흥동 118 37.4549894 126.8971601
604 경기도 과천시 주암동 92-1 37.4590154 127.0304790
605 서울특별시 관악구 신림동 57-13 37.4559322 126.9249239
606 경기도 양주시 덕계동 산30 37.8171086 127.0615411
607 서울특별시 노원구 중계동 356 37.6579375 127.0761865
608 서울특별시 노원구 상계동 164-9 37.6671760 127.0834861
609 대전광역시 중구 사정동 48-1 36.2926488 127.3875403
610 서울특별시 광진구 구의동 3-10 (구의2동) 37.5548700 127.1031900
613 강원도 양양군 강현면 38.1499400 128.6075870
614 대전광역시 중구 대사동 3-71 36.3044397 127.4225350
615 서울특별시 관악구 봉천동 4-9 37.4902852 126.9586969
617 강원도 평창군 진부면 37.6373320 128.5531000
618 경기도 동두천시 상패동 144번지 37.9085142 127.0419346
619 부산광역시 북구 만덕동 261 35.2234131 129.0362465
620 부산광역시 동구 초량동 34-1 35.1220027 129.0270561
622 강원도 홍천군 성산리 산18 37.7745525 127.9770210
623 경기도 의정부시 금오동 14 37.7630338 127.0786605
624 서울특별시 성북구 정릉동 87-1 37.6087476 126.9893938
625 경기도 파주시 파평면 덕천리86 37.9387175 126.8857420
626 충청북도 충주시 안림동 72-4 36.9612666 127.9560892
627 서울특별시 강동구 고덕동 287 37.5618448 127.1590420
628 경기도 양주시 회정동 336-1 37.8283132 127.0493934
629 경기도 동두천시 생연동 70 37.9003108 127.0697804
630 경기도 시흥시 정왕동 2138 37.3549266 126.7105851
631 강원도 춘천시 삼천동 60-1 37.8641861 127.7079103
632 부산광역시 금정구 서동 103 35.2240192 129.1037382
633 대전광역시 서구 정림동 2-1 36.3164513 127.3609468
634 부산광역시 사상구 모라동 35.1911376 128.9923628
635 부산광역시 서구 서대신동3가 7-3 35.1276577 129.0069625
636 서울특별시 은평구 갈현동 267-100 37.6240469 126.9088778
637 서울특별시 은평구 갈현동 267-100 37.6240469 126.9088778
641 경상남도 김해시 동상동 189 35.2474545 128.8847445
642 경상남도 김해시 동상동 190-1 35.2469329 128.8847850
643 부산광역시 금정구 금사동 544 35.2266181 129.1059763
647 경기도 하남시 초이동 산25-15 37.5388300 127.1672278
649 서울특별시 종로구 옥인동 3-14 37.5853125 126.9607916
650 인천광역시 서구 석남3동 산7 37.5087728 126.6858972
651 인천광역시 서구 석남동 12 37.5068440 126.6834723
652 서울특별시 양천구 신월동 85-4 37.5377611 126.8334489
654 부산광역시 부산진구 초읍동 98-1 35.1887713 129.0275593
655 인천광역시 부평구 산곡1동 179 37.5045828 126.6981280
657 부산광역시 부산진구 당감동 34 35.1698886 129.0135993
658 서울특별시 서대문구 연희동 2-15 37.5746124 126.9419089
659 서울특별시 노원구 상계동 산153-1 (상계3?4동) 37.6860574 127.0906362
660 강원도 홍천군 홍천읍 희망리31 37.6990965 127.8873007

# JSON Convert

In [0]:
df = pd.read_csv(path+'kwater_latlong.csv')
df.columns = ['index','name','address','state','lat','long']

data = df.to_json(orient='records', lines=True, force_ascii=False)
data = data.replace('\n',',')

json = '{{"data":[{data}]}}'.format(data=data)

with open(path + 'kwater.json', 'w') as outfile:
     outfile.write(json)